
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
// import ThemeRegistry from '../../utils/ThemeRegistry'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import theme from '../../utils/theme';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'MUI Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <AppRouterCacheProvider options={{ enableCssLayer: true }}>
        {/* <ThemeRegistry options={{ key: 'mui-theme' }}>{children}</ThemeRegistry> */}
      
        <ThemeProvider theme={theme}>
            {/* CssBaseline kickstart an elegant, consistent, and simple baseline to build upon. */}
            <CssBaseline />
            {children}
          </ThemeProvider>
      </AppRouterCacheProvider>
      </body>
    </html>
  )
}
